### ISSUE TITLE
Bug in comparison of science and dark ramp lengths in stcal/dark_current/dark_sub.py 

### ISSUE THREAD

**Issue by chriswillott** [spacetelescope/stcal#120]
Line 99 of https://github.com/spacetelescope/stcal/blob/main/src/stcal/dark_current/dark_sub.py is:

`sci_total_frames = sci_ngroups * (sci_nframes + sci_groupgap)`

but it should be

`sci_total_frames = sci_ngroups * sci_nframes + (sci_ngroups - 1) * sci_groupgap`

because there is one less gap than the number of groups.

This was discovered using NIRCam DEEP8 readout with sci_ngroups = 7. The dark reference file has 130 groups which is 2 frames more than the science data. However, the pipeline refused to attempt dark subtraction because the error above led to:
`Not enough data in dark reference file to match to science data.`

**Comment by hbushouse** [comment]
This problem is now being tracked in https://jira.stsci.edu/browse/JP-2938

**Comment by hbushouse** [comment]
@chriswillott I assume the same updated math should also apply to the next line of code, where the same info is calculated for the dark data in the reference file, although it's probably meaningless given that the convention is to always have the dark ref files based on data that use nframes=1 and groupgap=0. But I updated that line too, just for consistency. See #121

**Comment by chriswillott** [comment]
Yes.
