### ISSUE TITLE
Change logs in wrong sections

### ISSUE THREAD

**Issue by nden** [spacetelescope/stcal#122]
The Change log here, from #121 went in the wrong section.
https://github.com/spacetelescope/stcal/blob/main/CHANGES.rst#L61-L65

It needs to be under the `unreleased` section.

Also this one, from #116
https://github.com/spacetelescope/stcal/blob/main/CHANGES.rst#L22-L27

**Comment by zacharyburnett** [comment]
fixed in 94fe920b58d5edf99cfce7a8cc41354c7181c39b
